import LocalizedStrings from 'react-localization';

const strings = new LocalizedStrings({
    en:{
        //checkpoints
        checkpoints:'Checkpoints',
        checkpoint: 'Checkpoint',
        title:'Title',
        priority:'Priority',
        general:'General',
        description:'Description',
        detailedDescription:'Detailed description',
        emergencyDescription:'Description of what to do in case of a defect',
        normal:'Normal',
        important:'Important',
        riskOfInjury:'Risk of injury',
        ChoosePriority:'Please choose a priority',
        defaultCheckPoint: 'Use this checkpoint by default',

        //checklist
        checklists:'Checkpoints',
        checklist:'Checklist',
        name:'Name',
        addCheckpoint:'Add checkpoint',

        //elevators
        elevators:'Elevators',
        elevator:'Elevator',
        serialNumber:'Serial number',
        inspectionDays:'Inspection days',
        street:'Street',
        city:'City',
        manufacturer:'Manufacturer',
        constructionYear:'Construction year',
        location:'Location',
        type:'Type',
        barcode:'Barcode',
        elevatorStatus:'Elevator status',
        elevatorInOperation:'Elevator currently in operation',
        elevatorTest:'Elevator Test',
        elevatorAttendant:'Elevator Attendant',
        elevatorRepresentation:'Representation of the elevator attendant',
        checklistAndCheckpoints:'Checkpoints',
        emergency:'Notfall',
        emergencyService:'Emergency Service',
        emergencyCompanyNumber:'Emergency Company Number',
        additionalInformation:'Additional Information',
        emergencyNumber:'Emergency Number',
        date:'Date',

        //estate
        estate:'Estate',
        approach: 'Approach',
        facilityManagerName:'Facility manager name',
        address:'Address',
        houseNumber:'House number',
        postCode:'Post Code',
        country:'Country',
        phoneNumber:'Phone number',
        stakeholders:'Stakeholders',
        ownerManager:'Owner/Manager',
        addOwnerManager:'Add Owner/Manager',

        //estate-selfmanaged
        ownerSelfManaged:'Owner Selfmanaged',
        elevatorLimit: 'Elevator Limit',
        estatelimit: 'Estate Limit',
        userlimit: 'User Limit',
        limitError: 'Number value required!',
        limitPlaceholder: 'Limit number',
        limitNoMessage: 'No limit',
        

        //reports
        reports:'Reports',
        report:'Report',

        //user
        user:'User',
        firstName:'First Name',
        surname:'Surname',
        userName:'User Name',
        scope:'Scope',
        password:'Password',
        admin:'Admin',
        manager:'Manager',
        chooseRole:'Please choose a role',
        userStatus:'User status',
        addresses:'Addresses',
        typeOfAddress:'Type of address (private / business)',
        private:'private',
        business:'business',
        pleaseSelect:'Please select a value',
        emailAddress:'Email address',
        addEmailAddress:'Add an e-mail address',
        addres:'Address',
        notificationTime:'Notification Time',
        pleaseChooseTime:'Please choose a time',
        phoneNumbers:'Phone numbers',
        number:'Number',
        typeOfNumber:'Type of number (private / business / mobile)',
        mobile:'mobile',

        //placeholders
        searchForElevator:'Search For Elevator',
        search:'search',
        enterErrorDescription:'Enter error description (optional)',

        //header
        foundElevators:'Found elevators',
        noElevatorsFound:'No suitable elevators were found',
        todayDueElevators:'Today due elevators',
        noElevatorsDueToday:'There are no elevators due today',
        yourElevators:'Your elevators',
        notAssignedElevators:'They were not assigned elevators',
        noReportsYet:'There are no reports yet',

        //alerts
        saveAndClose:'Would you like to finish editing, save all changes and close the datasheet?',
        discardAndClose:'Do you want to stop editing and close the datasheet WITHOUT saving?',
        delete:'Do you want to delete the item irretrievably?',
        serverTimeoutTitle:'Server does not respond',
        serverTimeoutMessage:'The server could not be reached. Please check your internet connection or try again later.',
        noUsernameTitle:'No username specified',
        noUsernameMessage:'Please enter your username.',
        noPasswordTitle:'No password specified',
        noPasswordMessage:'Please enter your password.',
        allEmptyTitle:'No username and password entered',
        allEmptyMessage:'Please enter your username and password.',
        wrongUsernameTitle:'Wrong user name',
        wrongUsernameMessage:'The entered username could not be found..',
        wrongPasswordTitle:'Wrong password',
        wrongPasswordMessage:'The entered password is incorrect.',
        notFoundTitle:'Request could not be processed',
        notFoundMessage:'Please inform the system administrator.',
        logoutWarningTitle:'Do you really want to log out?',
        logoutWarningMessage:'You are about to log out. You can only log in again with an active internet connection.',
        limitErrorMessage: "You have reached the limit - upgrade your plan to add more!"
    },
    de: {
        //checkpoints
        checkpoints:'Prüfpunkte',
        checkpoint: 'Prüfpunkt',
        title:"Überschrift",
        priority:'Priorität',
        general:'Allgemein',
        description:'Kurzbeschreibung',
        detailedDescription:'Ausführliche Beschreibung',
        emergencyDescription:'Beschreibung was im Falle eines Mangels zu tun ist',
        normal:'Normal',
        important:'Wichtig',
        riskOfInjury:'Verletzungsgefahr',
        ChoosePriority:'Bitte wählen Sie eine Priorität',
        defaultCheckPoint: 'Prüfpunkt standardmäßig angewählt',

        //checklist
        checklists:'Prüfpunkte',
        checklist:'Prüfliste',
        name:'Name',
        addCheckpoint:'Prüfpunkt hinzufügen',

        //elevators
        elevators:'Aufzüge',
        elevator:'Aufzüg',
        serialNumber:'Seriennummer',
        inspectionDays:'Prüftage',
        street:'Straße',
        city:'Ort',
        manufacturer:'Hersteller',
        constructionYear:'Baujahr',
        location:'Standort',
        type:'Typ',
        barcode:'Barcode',
        elevatorStatus:'Aufzugstatus',
        elevatorInOperation:'Aufzug zur Zeit im Betrieb',
        elevatorTest:'Aufzug Prüfung',
        elevatorAttendant:'Aufzugwärter',
        elevatorRepresentation:'Vertretung des Aufzugwärters',
        checklistAndCheckpoints:'Prüfpunkte',
        emergency:'Notfall',
        emergencyService:'Notdienst',
        emergencyCompanyNumber:'Notdienstnummer',
        additionalInformation:'Weitere Informationen',
        emergencyNumber:'Notruf',
        date:'Datum',

        //estate
        estate:'Anwesen',
        approach: 'Anfahrt',
        facilityManagerName:'Hausmeister',
        address:'Anschrift',
        houseNumber:'Hausnummer',
        postCode:'Postleitzahl',
        country:'Land',
        phoneNumber:'Telefonnummer',
        stakeholders:'Verantwortliche',
        ownerManager:'Eigentümer/Verwalter',
        addOwnerManager:'Eigentümer/Verwalter hinzufügen',
        
        //estate-selfmanaged
        ownerSelfManaged:'Owner Selfmanaged',
        elevatorLimit: 'Elevator Limit',
        estatelimit: 'Estate Limit',
        userlimit: 'User Limit',
        limitError: 'Number value required!',
        limitPlaceholder: 'Limit number',
        limitNoMessage: 'No limit',

        //reports
        reports:'Protokolle',
        report:'Protokoll',

        //user
        user:'Benutzer',
        firstName:'Vorname',
        surname:'Nachname',
        userName:'Benutzername',
        scope:'Rolle',
        password:'Passwort',
        admin:'Admin',
        manager:'Manager',
        chooseRole:'Bitte wählen Sie eine Rolle',
        userStatus:'Nutzerstatus',
        addresses:'Adressen',
        typeOfAddress:'Art der Adresse (privat / geschäftlich)',
        private:'privat',
        business:'geschäftlich',
        pleaseSelect:'Bitte wählen Sie eine Art',
        emailAddress:'E-Mail Adressen',
        addEmailAddress:'E-Mail Adresse hinzufügen',
        addres:'Adresse',
        notificationTime:'Versanduhrzeit',
        pleaseChooseTime:'Bitte wählen Sie eine Uhrzeit',
        phoneNumbers:'Telefonnummern',
        number:'Nummer',
        typeOfNumber:'Art der Nummer (privat / geschäftlich / mobil)',
        mobile:'mobil',

        //placeholders
        searchForElevator:'Aufzug suchen',
        search:'suchen',
        enterErrorDescription:'Fehlerbeschreibung eintragen (optional)',

        //header
        foundElevators:'Gefundene Aufzüge',
        noElevatorsFound:'Es wurden keine passenden Aufzüge gefunden',
        todayDueElevators:'Heute fällige Aufzüge',
        noElevatorsDueToday:'Es sind heute keine Aufzüge fällig',
        yourElevators:'Ihre Aufzüge',
        notAssignedElevators:'Ihnen wurden keine Aufzüge zugewiesen',
        noReportsYet:'Es liegen noch keine Protokolle vor',

        //alerts
        saveAndClose:'Möchten Sie die Bearbeitung abschließen, alle Änderungen speichern und das Datenblatt schließen?',
        discardAndClose:'Möchten Sie die Bearbeitung abbrechen und das Datenblatt schließen OHNE zu speichern?',
        delete:'Möchten Sie das Element unwiederbringlich löschen?',
        serverTimeoutTitle:'Server nicht erreichbar',
        serverTimeoutMessage:'Der Server konnte nicht erreicht werden. Bitte überprüfen Sie Ihre Internetverbindung oder probieren Sie es ggf. zu einem spätern Zeitpunkt erneut.',
        noUsernameTitle:'Kein Benutzername angegeben',
        noUsernameMessage:'Bitte geben Sie Ihren Benutzernamen ein.',
        noPasswordTitle:'Kein Passwort angegeben',
        noPasswordMessage:'Bitte geben Sie Ihren Passwort ein.',
        allEmptyTitle:'Kein Benutzername und Passwort eingegeben',
        allEmptyMessage:'Bitte geben Sie Ihren Benutzernamen und Ihr Passwort ein.',
        wrongUsernameTitle:'Falscher Benutzernamen',
        wrongUsernameMessage:'Der eingegebene Benutzernamen konnte nicht gefunden werden.',
        wrongPasswordTitle:'Falsches Passwort',
        wrongPasswordMessage:'Das eingegebene Passwort ist nicht korrekt.',
        notFoundTitle:'Anfrage konnte nich verarbeitet werden',
        notFoundMessage:'Bitte infromieren Sie den Systemadministrator.',
        logoutWarningTitle:'Möchten Sie sich wirklich ausloggen?',
        logoutWarningMessage:'Sie sind im Begriff sich ausloggen. Sie können sich nur mit aktiver Internetverbindung wieder mit der einloggen.',
        limitErrorMessage: "Sie haben Ihr Limit erreicht - erhöhen Sie Ihr Limit durch ein Vertrags-Upgrade"
    }
});

strings.setLanguage('de');
// strings.setLanguage('en');

export default strings;